### ISSUE TITLE
Does not build without a git checkout?

### ISSUE THREAD

**Issue by quicklisp** [GrammaTech/sel#13]
Log is here: http://report.quicklisp.org/2020-01-18/failure-report/sel.html#software-evolution-library

I get this: `Git failed: (:ABSOLUTE "home" "quicklisp" "quicklisp-controller" "dist" "build-cache" "sel" "ccbcc6b0d57db2cbc2c5290543ecfbed79846f25" "sel-20200118-git") is not in a git repository.`

**Comment by eschulte** [comment]
I just pushed up what should be a fix for this issue.  Please reopen if this isn't sufficient.

Thanks for reporting!
