### ISSUE TITLE
System "gt/full" not found

### ISSUE THREAD

**Issue by ImanHosseini** [GrammaTech/sel#14]
SEL used to work fine but recently I cannot load it and I get this error: 'System "gt/full" not found'
This can be found in the quicklisp file: "https://git.grammatech.com/synthesis/gt.git" which is a repo which is not accessible [publicly].

**Comment by jaruchti** [comment]
Hi Iman,

We are working on getting these packages into quicklisp, but for the time being, you will probably need to clone the following two repositories into your quicklisp/local-projects folder to use SEL:

https://github.com/GrammaTech/functional-trees
https://github.com/GrammaTech/cl-utils

Please let me know if this does not resolve the issue,

- Jason

**Comment by ImanHosseini** [comment]
It worked!
Thank You
