### ISSUE TITLE
Outdated Installation instruction

### ISSUE THREAD

**Issue by stan6** [GrammaTech/sel#2]
I follow the installation instruction in this [https://grammatech.github.io/sel/Installation.html#Installation(https://grammatech.github.io/sel/Installation.html#Installation) to install the SEL library.

However, the instruction stated that cl-arrows recommends downloading from: [https://github.com/eschulte/cl-arrows](https://github.com/eschulte/cl-arrows) but it seems that the SEL library expects the cl-arrowz that can be downloaded from [https://github.com/eschulte/cl-arrowz](https://github.com/eschulte/cl-arrowz), which is a replacement of the cl-arrows library. 

There are two possible ways to resolve this issue:

1. Update the installation instruction to use https://github.com/eschulte/cl-arrowz
2. Update the dependency to be cl-arrows instead of cl-arrowz

**Comment by eschulte** [comment]
Thanks for this report.  I hope to update these instructions in the next week or so.  I'm currently working to get cl-arrowz and sel into quicklisp which should greatly simplify installation.

**Comment by jaruchti** [comment]
Note: https://github.com/GrammaTech/sel/commit/f8e34177d7d98b7378132f87e438c769c18d6574
